### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by anylayer** [Mufanc/Hunter#2]
Some errors have detailed explanations: E0405, E0412, E0425, E0433, E0463, E0531.
error: could not compile `memchr` (lib) due to 214 previous errors

**Comment by anylayer** [comment]
![image](https://github.com/Mufanc/DexHunter/assets/46556817/edb92c06-c455-4b0c-b3b2-d5e4b44376f4)

**Comment by Mufanc** [comment]
参考一下 [build.yml](https://github.com/Mufanc/DexHunter/blob/master/.github/workflows/build.yml)，可能是你的 NDK 版本太低了，换一个高版本的试试

**Comment by anylayer** [comment]
> 参考一下 [build.yml](https://github.com/Mufanc/DexHunter/blob/master/.github/workflows/build.yml)，可能是你的 NDK 版本太低了，换一个高版本的试试

谢谢答复，就是NDK版本过低的原因
